apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: intern-role-binding
  namespace: default
subjects:
- kind: User
  name: apache-intern
  namespace: default
roleRef:
  kind: Role
  name: intern-role
  apiGroup: rbac.authorization.k8s.io

