apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: intern-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "create"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["list", "watch"]

