apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-role-binding
  namespace: django-app
subjects:
- kind: User
  name: django-admin
  namespace: django-app
roleRef:
  kind: Role
  name: admin-role
  apiGroup: rbac.authorization.k8s.io

