apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: intern-role-binding
  namespace: django-app
subjects:
- kind: User
  name: notes-intern
  namespace: django-app
roleRef:
  kind: Role
  name: intern-role
  apiGroup: rbac.authorization.k8s.io

