kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: notes-app-pvc
  namespace: django-app
  labels:
    app: notes-app
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

